name: Pytest
description: Run pytest with a single database system.

inputs:
  database:
    description: A unique identifier for the database system tested against.
    required: true
  python-version:
    description: The Python version to use for testing.
    required: true
  environment:
    description: The pixi environment to use.
    required: true
  github-token:
    description: GitHub token to clone repositories other than this.
    required: true
  codecov-token:
    description: Codecov token to upload coverage information.
    required: true

runs:
  using: composite
  steps:
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659
      with:
        environments: ${{ inputs.environment }}
        activate-environment: true
    - name: Install repository
      run: pixi run postinstall
      shell: bash -el {0}
    - name: Run pytest
      run: pixi run test-coverage --color=yes
      shell: bash -el {0}
